@Adroit_v8_HostAddress = https://localhost:7271
@ACCESS_JWT=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkOTVkZTM1Ny1lNTdjLTQyYTctYjRlYy02MDc1YWM5NjBlYjAiLCJlbWFpbCI6Im9sYXNlaGluZGV5M0BnbWFpbC5jb20iLCJVc2VySWQiOiJkOTVkZTM1Ny1lNTdjLTQyYTctYjRlYy02MDc1YWM5NjBlYjAiLCJEZXNjcmlwdGlvbiI6InRlc3QiLCJGaXJzdE5hbWUiOiJZZXR1bmRlIiwiTGFzdE5hbWUiOiJPbGFzZWhpbmRlIiwiVXNlck5hbWUiOiJ5ZXR1c2VyIiwiSXNPdHBWZXJpZmllZCI6InRydWUiLCJDbGllbnRJZCI6ImVlMTNiODZiLTIxNDQtNGZiNy04OTEzLWU3MWU2OWYwZDdhMSIsIkFwcGxpY2F0aW9uSWQiOiI2MTBlZDIzNS1hMmZiLTQ1YjItYmYwMy1lODAzMGFkMjg2ZWIiLCJUb2tlbkV4cGlyYXRpb24iOiI2LzIzLzIwMjUgMTA6MjI6NTkgUE0iLCJqdGkiOiJhZDM4NWUzOC00ZmVjLTQwZmEtYTJlZS04MzExMjg3ZDlhNmYiLCJleHAiOjE3NTA3NDI1NzksImlzcyI6InllcyEhfiMiLCJhdWQiOiJ5ZXMhIX4jIn0.aGUXFUUMOYBx16nTFKIC6TtfLKDNSJcq9R91QXX0YY8
GET {{Adroit_v8_HostAddress}}/api/LoanApplication/Customer/getbyLoanId/APP-2816101624862-492284
Accept: application/json
Authorization: Bearer {{ACCESS_JWT}}
XApiKey:_*-+pgH7QzFH%^&!Jx4w46**fI@@#5Uzi4RvtTwlEXp_!*

###
