@Adroit_v8_HostAddress = https://localhost:7271
@ACCESS_JWT=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1YzFiMGI4Yy1jNjY3LTQ4YTgtYTg5ZC01MzJhMzdlNzIwYTgiLCJlbWFpbCI6Im9sYXNlaGluZGV5M0BnbWFpbC5jb20iLCJVc2VySWQiOiI1YzFiMGI4Yy1jNjY3LTQ4YTgtYTg5ZC01MzJhMzdlNzIwYTgiLCJEZXNjcmlwdGlvbiI6ImdmZGdmZGdoZiIsIkZpcnN0TmFtZSI6ImFkcm9pdHVzZXIiLCJMYXN0TmFtZSI6ImFkcm9pdHVzZXIiLCJVc2VyTmFtZSI6ImFkcm9pdHVzZXIiLCJJc090cFZlcmlmaWVkIjoidHJ1ZSIsIkNsaWVudElkIjoiNjg3MDFhYzMtNWMxZi00Y2ExLWExZTUtNDg4ZmZjN2QyOWRmIiwiQXBwbGljYXRpb25JZCI6ImNiMjE4NzY3LWI0NTUtNDEzMC1hMzZiLTdmZmJhNjAwZjU1MCIsIlRva2VuRXhwaXJhdGlvbiI6IjUvMjgvMjAyNSAxMTo0NDoyNyBBTSIsImp0aSI6IjNlOThkMjlkLTcyOWItNDNiYy05OWYyLTZiOTFiNDc4YjQ3NiIsImV4cCI6MTc0ODQ1Nzg2NywiaXNzIjoieWVzISF-IyIsImF1ZCI6InllcyEhfiMifQ.sqMVJBbbGXdqdK3wSPlzYe3aWpdy8ET_JG8EBytIf68
GET {{Adroit_v8_HostAddress}}/api/ApplicationPermission/get_user_application_pages_permission/5c1b0b8c-c667-48a8-a89d-532a37e720a8
Accept: application/json
Authorization: Bearer {{ACCESS_JWT}}
XApiKey:_*-+pgH7QzFH%^&!Jx4w46**fI@@#5Uzi4RvtTwlEXp_!*

###
