// <auto-generated />
using System;
using Adroit_v8.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Adroit_v8.Migrations
{
    [DbContext(typeof(CreditWaveContext))]
    [Migration("20240326153653_gddcfgvctfygbjnkl")]
    partial class gddcfgvctfygbjnkl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Adroit_v8.Models.Administration.Adminproduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("AsEndDate")
                        .HasColumnType("boolean");

                    b.Property<string>("Createdby")
                        .HasColumnType("text");

                    b.Property<DateTime>("Datecreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("Enddate")
                        .HasColumnType("date");

                    b.Property<string>("InterestRate")
                        .HasColumnType("text");

                    b.Property<int>("Isdeleted")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Maximuimamount")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Minimuimamount")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("Startdate")
                        .HasColumnType("date");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("Tenor")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clientid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Adminproducts");
                });

            modelBuilder.Entity("Adroit_v8.Models.Administration.LoanTenor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Createdby")
                        .HasColumnType("text");

                    b.Property<int>("Isdeleted")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clientid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LoanTenors");
                });

            modelBuilder.Entity("Adroit_v8.Models.Administration.ProductLateFee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Createdby")
                        .HasColumnType("text");

                    b.Property<string>("FeeFrequency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("FixedPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("GracePeriod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Isdeleted")
                        .HasColumnType("integer");

                    b.Property<string>("LateFeePrincipal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LateFeeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clientid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProductLateFees");
                });

            modelBuilder.Entity("Adroit_v8.Models.Administration.ProductLoanProcessingFee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Createdby")
                        .HasColumnType("text");

                    b.Property<decimal>("FixedPrice")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsFixedPrice")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOptInProcessingFee")
                        .HasColumnType("boolean");

                    b.Property<int>("Isdeleted")
                        .HasColumnType("integer");

                    b.Property<decimal>("Principal")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clientid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProductLoanProcessingFees");
                });

            modelBuilder.Entity("Adroit_v8.Models.Administration.UnderwriterLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Createdby")
                        .HasColumnType("text");

                    b.Property<DateTime>("Datecreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Isdeleted")
                        .HasColumnType("integer");

                    b.Property<string>("Loanrange")
                        .HasColumnType("text");

                    b.Property<decimal?>("MaximuimAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MinimuimAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clientid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UnderwriterLevels");
                });

            modelBuilder.Entity("Adroit_v8.Models.CRM.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AlternativePhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("Bvn")
                        .HasColumnType("text")
                        .HasColumnName("BVN");

                    b.Property<string>("ClientId")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CustomerRef")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("text");

                    b.Property<int?>("EducationalLevelId")
                        .HasColumnType("integer");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("text");

                    b.Property<string>("EscrowAccountNumber")
                        .HasColumnType("text");

                    b.Property<string>("FacebookId")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<int?>("GenderId")
                        .HasColumnType("integer");

                    b.Property<int?>("HasValidBvn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("HasValidBVN")
                        .HasDefaultValueSql("0");

                    b.Property<int?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("0");

                    b.Property<int?>("IsBlackListedCustomer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("0");

                    b.Property<int?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("0");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("LinkedinId")
                        .HasColumnType("text");

                    b.Property<int?>("MaritalStatusId")
                        .HasColumnType("integer");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<string>("Nin")
                        .HasColumnType("text")
                        .HasColumnName("NIN");

                    b.Property<int?>("NumberOfDependent")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<int?>("RegistrationChannelId")
                        .HasColumnType("integer");

                    b.Property<int?>("RegistrationStageId")
                        .HasColumnType("integer");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("TitleId")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueId")
                        .HasColumnType("text");

                    b.Property<string>("WhatsappNumber")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("Customer_pkey");

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("Adroit_v8.Models.UtilityModel.AdminRegularLoanCharge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChargeAmount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Createdby")
                        .HasColumnType("text");

                    b.Property<string>("EmploymentTypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPercentage")
                        .HasColumnType("boolean");

                    b.Property<int>("Isdeleted")
                        .HasColumnType("integer");

                    b.Property<decimal>("LoanAmountFrom")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LoanAmountTo")
                        .HasColumnType("numeric");

                    b.Property<int>("LoanTenorid")
                        .HasColumnType("integer");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clientid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AdminRegularLoanCharges");
                });

            modelBuilder.Entity("Adroit_v8.Models.UtilityModel.AdminRegularLoanInterestRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Createdby")
                        .HasColumnType("text");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmploymentTypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InterestRate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Isdeleted")
                        .HasColumnType("integer");

                    b.Property<decimal>("LoanAmountFrom")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LoanAmountTo")
                        .HasColumnType("numeric");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clientid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AdminRegularLoanInterestRates");
                });

            modelBuilder.Entity("Adroit_v8.Models.UtilityModel.Applicationchannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Createdby")
                        .HasColumnType("text");

                    b.Property<int>("Isdeleted")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clientid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Applicationchannels");
                });

            modelBuilder.Entity("Adroit_v8.Models.UtilityModel.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BankCode")
                        .HasColumnType("text");

                    b.Property<string>("Createdby")
                        .HasColumnType("text");

                    b.Property<int>("Isdeleted")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clientid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("Adroit_v8.Models.UtilityModel.DeclineReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Createdby")
                        .HasColumnType("text");

                    b.Property<int>("Isdeleted")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clientid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DeclineReasons");
                });

            modelBuilder.Entity("Adroit_v8.Models.UtilityModel.Educationallevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Createdby")
                        .HasColumnType("text");

                    b.Property<int>("Isdeleted")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clientid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Educationallevels");
                });

            modelBuilder.Entity("Adroit_v8.Models.UtilityModel.EmploymentSector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Createdby")
                        .HasColumnType("text");

                    b.Property<int>("Isdeleted")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clientid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EmploymentSectors");
                });

            modelBuilder.Entity("Adroit_v8.Models.UtilityModel.Employmentstatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Createdby")
                        .HasColumnType("text");

                    b.Property<int>("Isdeleted")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clientid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Employmentstatuses");
                });

            modelBuilder.Entity("Adroit_v8.Models.UtilityModel.Employmenttype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Createdby")
                        .HasColumnType("text");

                    b.Property<int>("Isdeleted")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clientid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Employmenttypes");
                });

            modelBuilder.Entity("Adroit_v8.Models.UtilityModel.FeeFrequency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Createdby")
                        .HasColumnType("text");

                    b.Property<int>("Isdeleted")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clientid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FeeFrequencys");
                });

            modelBuilder.Entity("Adroit_v8.Models.UtilityModel.FixedDepositAmountRange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Createdby")
                        .HasColumnType("text");

                    b.Property<string>("FromAmount")
                        .HasColumnType("text");

                    b.Property<int>("Isdeleted")
                        .HasColumnType("integer");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("ToAmount")
                        .HasColumnType("text");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clientid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FixedDepositAmountRanges");
                });

            modelBuilder.Entity("Adroit_v8.Models.UtilityModel.FixedDepositInterestRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Createdby")
                        .HasColumnType("text");

                    b.Property<int>("FixedDepositTenor")
                        .HasColumnType("integer");

                    b.Property<string>("InterestRate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Isdeleted")
                        .HasColumnType("integer");

                    b.Property<decimal>("LoanAmountFrom")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LoanAmountTo")
                        .HasColumnType("numeric");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clientid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FixedDepositInterestRate");
                });

            modelBuilder.Entity("Adroit_v8.Models.UtilityModel.FixedDepositPreliquidationCharges", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AmountCharge")
                        .HasColumnType("text");

                    b.Property<string>("Createdby")
                        .HasColumnType("text");

                    b.Property<string>("FromAmount")
                        .HasColumnType("text");

                    b.Property<string>("IsPercentage")
                        .HasColumnType("text");

                    b.Property<int>("Isdeleted")
                        .HasColumnType("integer");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("ToAmount")
                        .HasColumnType("text");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clientid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FixedDepositPreliquidationChargeses");
                });

            modelBuilder.Entity("Adroit_v8.Models.UtilityModel.FixedDepositStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Createdby")
                        .HasColumnType("text");

                    b.Property<int>("Isdeleted")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clientid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FixedDepositStatuses");
                });

            modelBuilder.Entity("Adroit_v8.Models.UtilityModel.FixedDepositTenor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Createdby")
                        .HasColumnType("text");

                    b.Property<string>("Days")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Isdeleted")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clientid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FixedDepositTenors");
                });

            modelBuilder.Entity("Adroit_v8.Models.UtilityModel.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Createdby")
                        .HasColumnType("text");

                    b.Property<int>("Isdeleted")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clientid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genders");
                });

            modelBuilder.Entity("Adroit_v8.Models.UtilityModel.GovernmentIDCardType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Createdby")
                        .HasColumnType("text");

                    b.Property<int>("Isdeleted")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clientid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GovernmentIDCardTypes");
                });

            modelBuilder.Entity("Adroit_v8.Models.UtilityModel.LateFeePrincipal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Createdby")
                        .HasColumnType("text");

                    b.Property<int>("Isdeleted")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clientid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LateFeePrincipals");
                });

            modelBuilder.Entity("Adroit_v8.Models.UtilityModel.LateFeeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Createdby")
                        .HasColumnType("text");

                    b.Property<int>("Isdeleted")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clientid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LateFeeTypes");
                });

            modelBuilder.Entity("Adroit_v8.Models.UtilityModel.Lga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Createdby")
                        .HasColumnType("text");

                    b.Property<int>("Isdeleted")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clientid")
                        .HasColumnType("text");

                    b.Property<string>("stateid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Lgas");
                });

            modelBuilder.Entity("Adroit_v8.Models.UtilityModel.Maritalstatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Createdby")
                        .HasColumnType("text");

                    b.Property<int>("Isdeleted")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clientid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Maritalstatuses");
                });

            modelBuilder.Entity("Adroit_v8.Models.UtilityModel.Nationality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Createdby")
                        .HasColumnType("text");

                    b.Property<int>("Isdeleted")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clientid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Nationalities");
                });

            modelBuilder.Entity("Adroit_v8.Models.UtilityModel.Noofdependant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Createdby")
                        .HasColumnType("text");

                    b.Property<int>("Isdeleted")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clientid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Noofdependants");
                });

            modelBuilder.Entity("Adroit_v8.Models.UtilityModel.Noofyearofresidence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Createdby")
                        .HasColumnType("text");

                    b.Property<int>("Isdeleted")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clientid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Noofyearofresidences");
                });

            modelBuilder.Entity("Adroit_v8.Models.UtilityModel.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Createdby")
                        .HasColumnType("text");

                    b.Property<int>("Isdeleted")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clientid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("Adroit_v8.Models.UtilityModel.RegularLoanCharge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChargeAmount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Createdby")
                        .HasColumnType("text");

                    b.Property<string>("EmploymentTypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPercentage")
                        .HasColumnType("boolean");

                    b.Property<int>("Isdeleted")
                        .HasColumnType("integer");

                    b.Property<decimal>("LoanAmountFrom")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LoanAmountTo")
                        .HasColumnType("numeric");

                    b.Property<int>("LoanTenorid")
                        .HasColumnType("integer");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clientid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RegularLoanCharges");
                });

            modelBuilder.Entity("Adroit_v8.Models.UtilityModel.RegularLoanInterestRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Createdby")
                        .HasColumnType("text");

                    b.Property<string>("EmploymentTypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InterestRate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Isdeleted")
                        .HasColumnType("integer");

                    b.Property<decimal>("LoanAmountFrom")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LoanAmountTo")
                        .HasColumnType("numeric");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clientid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RegularLoanInterestRates");
                });

            modelBuilder.Entity("Adroit_v8.Models.UtilityModel.RegularLoanTenor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Createdby")
                        .HasColumnType("text");

                    b.Property<int>("Isdeleted")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clientid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RegularLoanTenors");
                });

            modelBuilder.Entity("Adroit_v8.Models.UtilityModel.Residentialstatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Createdby")
                        .HasColumnType("text");

                    b.Property<int>("Isdeleted")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clientid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Residentialstatuses");
                });

            modelBuilder.Entity("Adroit_v8.Models.UtilityModel.Salarypaymentdate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Createdby")
                        .HasColumnType("text");

                    b.Property<int>("Isdeleted")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clientid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Salarypaymentdates");
                });

            modelBuilder.Entity("Adroit_v8.Models.UtilityModel.Salaryrange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Createdby")
                        .HasColumnType("text");

                    b.Property<int>("Isdeleted")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clientid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Salaryranges");
                });

            modelBuilder.Entity("Adroit_v8.Models.UtilityModel.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Countryid")
                        .HasColumnType("text")
                        .HasColumnName("countryid");

                    b.Property<string>("Createdby")
                        .HasColumnType("text");

                    b.Property<int>("Isdeleted")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clientid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("States");
                });

            modelBuilder.Entity("Adroit_v8.Models.UtilityModel.Title", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Createdby")
                        .HasColumnType("text");

                    b.Property<int>("Isdeleted")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clientid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Titles");
                });

            modelBuilder.Entity("Adroit_v8.Models.UtilityModel.UtilityBillType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Createdby")
                        .HasColumnType("text");

                    b.Property<int>("Isdeleted")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clientid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UtilityBillTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
